# Generated by Django 3.0.6 on 2020-05-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=120)),
                ('prioridade', models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baixa')], max_length=1)),
            ],
        ),
    ]
